sudo: false
language: node_js
cache:
  directories:
  - node_modules
script: npm run ci

deploy:
  - provider: script
    script: script/deploy.sh
    skip_cleanup: true
    on:
      branch: staging
  - provider: script
    script: script/deploy.sh
    skip_cleanup: true
    on:
      branch: master
